# TravisCI configuration for voku/Stringy

if: "branch = master"

language: "php"
os:
  - "linux"
dist: "bionic"

php:
  - "8.0"
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"

jobs:
  fast_finish: true
  include:
    - php: "7.0"
      dist: "xenial"
    - name: "Static analysis"
      php: "7.1"
      script:
        - "travis_retry composer require --no-interaction --dev phpstan/phpstan"
        - "vendor/bin/phpstan analyse"
      after_script: "skip"
  allow_failures:
    - php: "8.0"

git:
  depth: 2

cache:
  directories:
    - "${HOME}/.composer/cache"

before_install:
  # Disable PHP extensions
  - "phpenv config-rm mbstring.ini"
  - "phpenv config-rm intl.ini"
  - "phpenv config-rm iconv.ini"
  - "mkdir -p build/logs"
  
install: 
  - "travis_retry composer update --no-interaction --prefer-source --optimize-autoloader"

script:
  - "vendor/bin/phpunit --verbose"

after_script:
  # Upload to Coveralls
  - "travis_retry composer require --no-interaction --prefer-source --dev satooshi/php-coveralls"
  - "vendor/bin/coveralls -v"
  # Upload to Scrutinizer
  - "wget https://scrutinizer-ci.com/ocular.phar"
  - "php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml"
  # Upload to Codecov
  - "bash <(curl -s https://codecov.io/bash)"
